version: '3.5'
services:

  master:
      restart: always
      image: postgres:13
      container_name: primary_postgres
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=fa_chat
      volumes:
        - ./data/master:/var/lib/postgresql/data
      networks:
        mynetwork:
          ipv4_address: 179.19.0.101

  slave:
      restart: always
      image: postgres:13
      container_name: slave_postgres
      ports:
        - "5434:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      volumes:
        - ./data/slave:/var/lib/postgresql/data
      networks:
        mynetwork:
          ipv4_address: 179.19.0.102

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
      - subnet: 179.19.0.0/24